"""add indexes on players table

Revision ID: 97c09b770514
Revises: 06e14ab4dd26
Create Date: 2026-03-31 00:17:50.944221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97c09b770514'
down_revision: Union[str, Sequence[str], None] = '06e14ab4dd26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_players_active', 'players', ['is_active'], unique=False, postgresql_where=sa.text('is_active IS true'))
    op.create_index('idx_players_icons_json', 'players', ['icons_json'], unique=False, postgresql_using='gin')
    op.create_index('idx_players_not_deleted', 'players', ['deleted_at', sa.literal_column('(deleted_at IS NULL)')], unique=False)
    op.create_index('idx_players_registered_at', 'players', ['registered_at'], unique=False)
    op.create_index('idx_players_settings_json', 'players', ['settings_json'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_players_settings_json', table_name='players', postgresql_using='gin')
    op.drop_index('idx_players_registered_at', table_name='players')
    op.drop_index('idx_players_not_deleted', table_name='players')
    op.drop_index('idx_players_icons_json', table_name='players', postgresql_using='gin')
    op.drop_index('idx_players_active', table_name='players', postgresql_where=sa.text('is_active IS true'))
    # ### end Alembic commands ###
